{{- if or (eq .Capabilities.KubeVersion.Minor "17") (eq .Capabilities.KubeVersion.Minor "17+")}}
apiVersion: storage.k8s.io/v1beta1
{{- else }}
apiVersion: storage.k8s.io/v1
{{- end }}
kind: CSIDriver
metadata:
    name: csi-isilon.dellemc.com
spec:
    attachRequired: true
    podInfoOnMount: true
    volumeLifecycleModes: 
    - Persistent
    - Ephemeral
