name: Weekly License Header Check

on:
  workflow_dispatch:
jobs:
  license-check:
    name: Run License Header Checker
    uses: dell/common-github-actions/.github/workflows/license-checker.yaml@main
    secrets: inherit
